// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrWQwYDeOF4be9bOGD1ngBXBJ7qQ20sAQ',
    appId: '1:944579461272:web:465da8c023b521aaa0d0ed',
    messagingSenderId: '944579461272',
    projectId: 'al-faseelah-parent-app',
    authDomain: 'al-faseelah-parent-app.firebaseapp.com',
    storageBucket: 'al-faseelah-parent-app.firebasestorage.app',
    measurementId: 'G-T0TKVLKHZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATMNHl1mQiEnwZfH5xAOseGAfEIghcohw',
    appId: '1:944579461272:android:ea67d9dc41c6d7a0a0d0ed',
    messagingSenderId: '944579461272',
    projectId: 'al-faseelah-parent-app',
    storageBucket: 'al-faseelah-parent-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrWQwYDeOF4be9bOGD1ngBXBJ7qQ20sAQ',
    appId: '1:944579461272:web:5f1f2d64d13e5324a0d0ed',
    messagingSenderId: '944579461272',
    projectId: 'al-faseelah-parent-app',
    authDomain: 'al-faseelah-parent-app.firebaseapp.com',
    storageBucket: 'al-faseelah-parent-app.firebasestorage.app',
    measurementId: 'G-2JCPV74G36',
  );
}
